
#-------
#default
#-------

# MARIADB : poc pemdb1
pemdb1:
  datasource:
    # driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    defaultAutoCommit: false
    maxActive: 30
    maxIdle: 20
    initialSize: 10
    validationQuery: select 1 from dual
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 3000
  jpa:
    hibernate:
      database: mariadb
      # 절대 바꾸지 말 것!!! ddl-auto: none으로 고정
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        # dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    open-in-view: false

---
#local
spring:
  config:
    activate:
      on-profile: db-local
      
pemdb1:
  datasource:
    username: pem
    password: tndfPans2013^_
    # jdbc-url: jdbc:mariadb://175.126.73.136:3306/pemdb1
    jdbc-url: jdbc:log4jdbc:mariadb://175.126.73.136:3306/pemdb1
    # jdbc-url: jdbc:log4jdbc:mysql://192.168.100.216:3307/pemdb1?useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
---
#dev
spring:
  config:
    activate:
      on-profile: db-dev

pemdb1:
  datasource:
    username: pem
    password: tndfPans2013^_
    jdbc-url: jdbc:mariadb://175.126.73.136:3306/pemdb1

---
#prod
spring:
  config:
    activate:
      on-profile: db-prod

pemdb1:
  datasource:
    username: pem
    password: tndfPans2013^_
    jdbc-url: jdbc:mariadb://175.126.73.136:3306/pemdb1
